# SPDX-FileCopyrightText: Copyright (c) 2021-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: up
'on':
  push:
    branches:
      - master
    tags:
      - '*'
permissions:
  contents: write
  pull-requests: write
jobs:
  up:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - run: |-
          git fetch --tags --force && \
          latest=$(git tag --sort=creatordate | tail -1) && \
          export latest && \
          sed -E -i "s/latexmk-action@.+$/latexmk-action@${latest}/g" README.md
      - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7
        with:
          sign-commits: true
          branch: version-up
          commit-message: 'new version ${{ env.latest }} in README'
          delete-branch: true
          title: 'New version ${{ env.latest }} in README'
          assignees: yegor256
          base: master
